version: "3.7"
services:
  rabbit:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    build: .
    depends_on:
      - rabbit
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    ports:
      - "8080:8080"